from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from starlette.requests import Request
from dto.email import EmailRequest
from dto.fechamento_requests import FechamentoRequest
from repository.caixa import caixa_ordenado_por_id_desc
from repository.concialicao import concialiacao_ordenadas_por_id_desc
from repository.despesas import despesas_ordenadas_por_id_desc
from service.drive_service import get_last_file_from_drive
from service.email_service import enviar_email, read_emails_from_gmail
from service.fechamento_despesas import fechar_despesas
from service.fechamento_pagamento import fechar_pagamentos

app = FastAPI()
templates = Jinja2Templates(directory="templates")


# About page route
@app.get("/about")
def about() -> dict[str, str]:
    return {"message": "This is the about page."}

@app.get("/mail")
def mail() -> list:
    return read_emails_from_gmail()

@app.get("/drive")
def mail() -> list:
    return get_last_file_from_drive()

@app.get("/despesas")
def despesas() -> list:
    return despesas_ordenadas_por_id_desc()

@app.get("/caixa")
def caixa() -> list:
    return caixa_ordenado_por_id_desc()

@app.get("/concialiacao")
def concialiacao() -> list:
    return concialiacao_ordenadas_por_id_desc()

@app.post("/fechamento-despesas")
def fechamento(request: FechamentoRequest = FechamentoRequest()) -> dict:
    return fechar_despesas(request.data_inicial, request.data_final)

@app.post("/fechamento-pagamentos")
def fechamento(request: FechamentoRequest = FechamentoRequest()) -> dict:
    return fechar_pagamentos(request.data_inicial, request.data_final)

@app.get("/", response_class=HTMLResponse)
async def read_home(request: Request):
    despesas = concialiacao_ordenadas_por_id_desc()
    return templates.TemplateResponse("home.html", {"request": request, "despesas": despesas})

@app.post("/send-email")
def send_email(request: EmailRequest) -> dict:
    
    templates = Jinja2Templates(directory="templates")
    
    context = {
        "request": request,
        "mes": "Fevereiro",
        "valor": "150,00",
        "codigo_pix": "1234567890",
        "imagem_base64": "iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAAAklEQVR4AewaftIAAA3TSURBVO3BgW0sS5AkQY8E9Vc59uMEqL7N2sYM+dws/Q+SJP0vDZIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC388AWS8Ne15VYSbrTlJAknbbmVhDe15UYS/gVt+euS8Ne15ZMGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWfvgF2vLtkvBpbTlJwo0k/HVteZKEk7bcSMLbknDSlhtJuNGWt7Xl2yXhmw2SJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC388Ack4W1teVMSbiXhpC0nSbjRlltJuJGET0vCJ7Xl27Xl2yXhbW35zQZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWftCv0ZaTJNxoy6e15ZOScKstN5Jw0paTJDxpy0kSTtpyIwknbdH3GyRJWhgkSVoYJElaGCRJWhgkSVoYJElaGCRJWvhBf0ZbTpJw0pZvl4Q3teVJEk6ScKMtN9ryJAknbXlTW/T7DZIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLfzwB7TlX5CEG205ScKnteVGW06S8GltOUnCSVu+XVtuJOFJW97UFp0NkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQt/PALJEHQlpMkvKktJ0l40paTJJy05SQJJ205ScKTtpwk4ZOS8KQtJ0k4actJEk7a8mlJ0J1BkqSFQZKkhUGSpIVBkqSFQZKkhUGSpIVBkqSFH75AW/S+JLypLbfa8klteZKEk7Z8uySctOVGW06S8La26F2DJEkLgyRJC4MkSQuDJEkLgyRJC4MkSQuDJEkLP3yBJJy05SQJ364tJ215W1s+LQlvasu3S8KNJJy05UkSTpJwoy0nbXlbEr5dW36zQZKkhUGSpIVBkqSFQZKkhUGSpIVBkqSFQZKkhUGSpIX0P3xYEm605UkSTtry2yXhTW15WxLe1JaTJLytLSdJOGnLSRLe1pZvl4STtpwk4aQtt5Jw0pZvNkiStDBIkrQwSJK0MEiStDBIkrQwSJK0MEiStPDDF2jLSRJuteUkCZ/UlidJOGnLSRJuJOGkLbfacpKEN7XlSRL0riTcastJEk7a8ra2nCThpC2fNEiStDBIkrQwSJK0MEiStDBIkrQwSJK0MEiStPDDF0jC25Jw0paTJJy05SQJJ0m4lYSTtpwk4aQtt5Jw0pZPSsKTtpwk4U1JOGmLIAk3knDSln/dIEnSwiBJ0sIgSdLCIEnSwiBJ0sIgSdLCIEnSwg9foC03kvCkLW9KwklbPi0JJ235tCS8KQm3knDSlt8uCZ/Ulrcl4du15ZsNkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQtpP/hw5LwtrZ8syTcastJEm605SQJT9pykoQbbfnXJeFWW06ScKMtb0vCSVtOkvC2tpwk4aQtnzRIkrQwSJK0MEiStDBIkrQwSJK0MEiStDBIkrTwg/6/JOFNbXmShDe15UZbbrXlRhJO2nKShFttOUnCt0vCSVtOknCShFttOWnLJ7XlSRJO2vLNBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhZ++Eck4U1tOUnCX5eEW235pLY8ScJJEm605SQJb2vLSRJutOUkCU+ScKMtb0rCk7b8ZoMkSQuDJEkLgyRJC4MkSQuDJEkLgyRJC4MkSQs//AJtuZWEG205ScJJW06S8KQtJ0m4kYSTtpy05VYSPikJT9pyIwk32nIrCSdJ+O3acpKEG205ScKTJJy05ZsNkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQt/PAHJOFJW06ScKMtJ0k4acuTJHyzJDxpy422nCThJAknbbmVhBtJOGnLSRKetOVGEk7acqMtT5Jwoy1vasuTJPxmgyRJC4MkSQuDJEkLgyRJC4MkSQuDJEkLgyRJCz98gbacJOGkLW9Lwo22nCTh09pyoy3fri0nSXjSlhtteVNbniThX5eEk7bcSMKtJJy05ZMGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWfvgCSThpy0kSnrTlpC1vSsJJW54k4UZbbiThbW250ZYbbbnVlpMknLTlRhKetOUkCTeScNKWb5eEk7b86wZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhZ++AJtudGWJ0k4acuNJJy05W1teVNbTpLwaUk4actJEt7WlpMknLTlpC1PknDSljcl4aQtt5Jw0pYbSfjXDZIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC388AWScNKWkyQ8actJEk7actKWkyTcasuNJJy05bdry0kSTtry7ZLwtiSctOUkCSdtOUnCk7a8KQknbbmVhJO2fLNBkqSFQZKkhUGSpIVBkqSFQZKkhUGSpIVBkqSFH/T/tOVGEk7acpKEJ0m40ZZvl4Rvl4STtpwk4aQtJ0l4W1tOknDSFt1LwklbPmmQJGlhkCRpYZAkaWGQJGlhkCRpYZAkaWGQJGnhhz+gLU+ScKMtJ2250ZZbSThJwklbTpJw0pYnSThpyycl4UlbbrTlJAknbTlJwq0knLTl05Jw0pZPSsKTtpwk4ZsNkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQt/PAF2nKShG+XhJO2nCThSVtutOXT2vJJSThpy5MkfFISbrXlJAknSXhTW54k4SQJN9rytiSctOWbDZIkLQySJC0MkiQtDJIkLQySJC0MkiQtDJIkLaT/4ZdLwqe15SQJJ215koSTtnxSEp605SQJJ235tCS8qS03kvC2tpwk4aQtJ0l40pbfLgknbflmgyRJC4MkSQuDJEkLgyRJC4MkSQuDJEkLgyRJCz/o/0QSPi0JJ215U1ueJOFGEm605SQJt9ry7dpykoQbbbnRlrcl4aQtJ0n41w2SJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQt/PAFkvC2tpwk4aQtN5JwkoTfLgm/XVtuJeGkLSdJOGnLSVs+LQknbbmVhDcl4aQtt5Lwmw2SJC0MkiQtDJIkLQySJC0MkiQtDJIkLQySJC388I9IwklbbiThRltuJeFGEk7actKWJ0k4acuNJLwtCTeScNKWT2vLJyXhSVvelIQbSbiVhJO2fNIgSdLCIEnSwiBJ0sIgSdLCIEnSwiBJ0sIgSdLCD79AW24l4UYSTtpyIwm32vKmJNxqy0kSTtpy0pYbSbjVlhtJOGnLrSR8s7Y8ScKNtrypLU+S8JsNkiQtDJIkLQySJC0MkiQtDJIkLQySJC0MkiQt/PCPaMuNtpwk4W1tOUnCjbacJOGkLU+S8KYk3GjLp7XlbW15UxJOknDSlidt+eva8s0GSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWfvgDkvCkLSdJuNGWtyXhmyXhSVtuJOFNSXjSljcl4aQtb0vCjbZ8WhL0rkGSpIVBkqSFQZKkhUGSpIVBkqSFQZKkhUGSpIUf/hFJuNGWkySctOUkCbfa8u2ScNKWk7bcSMKtJJy05UZbTpJw0pZPS8Jfl4STtvx1gyRJC4MkSQuDJEkLgyRJC4MkSQuDJEkLgyRJC4MkSQvpf9DHJeFWW24k4aQtJ0n4dm25lYSTtpwk4dPa8klJuNWWNyXhRlv+ukGSpIVBkqSFQZKkhUGSpIVBkqSFQZKkhUGSpIUfvkAS/rq2nLTlSRI+KQknbbmVhBtt0ecl4aQtJ0m4lYSTttxoy0kS3taWTxokSVoYJElaGCRJWhgkSVoYJElaGCRJWhgkSVr44Rdoy7dLwo0kvC0JN9rytracJOEkCSdteVsSTtpykoQbbXmShJO23GjLp7Xlk9ryJAknbflmgyRJC4MkSQuDJEkLgyRJC4MkSQuDJEkLgyRJCz/8AUl4W1s+rS2/XRJutOVGEk7acqstN9pyIwmfloSTttxKwicl4VZbfrNBkqSFQZKkhUGSpIVBkqSFQZKkhUGSpIVBkqSFH/RrJOFGW06ScCMJT9pykoSTJNxoy9uScNKWG0k4acutJNxoy0kS3taWG0m40ZYnSThpyzcbJElaGCRJWhgkSVoYJElaGCRJWhgkSVoYJEla+EF/Rls+qS1PknDSlpMknLTl09pyIwmf1pYbSThpy0kSnrTlmyXhrxskSVoYJElaGCRJWhgkSVoYJElaGCRJWhgkSVoYJEla+OEPaMtv15YnSbiRhBtJeFsS3pSEk7a8LQknbbmRhCdtOUnCm5Jw0pYnSThpy0kSbrTlXzdIkrQwSJK0MEiStDBIkrQwSJK0MEiStDBIkrTwwy+QhL8uCU/acpKEG205ScKttvx2bbnRlpMkfFpbTpJwoy232nKShDcl4aQtT5Jw0pZvNkiStDBIkrQwSJK0MEiStDBIkrQwSJK0MEiStJD+B0mS/pcGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIWBkmSFgZJkhYGSZIW/ge9cYx3Tlhf6wAAAABJRU5ErkJggg==" 
    }

    request.body = templates.TemplateResponse("email.html", context).body.decode("utf-8")
    
    enviar_email(request.subject, request.body, request.recipient)
    return {"message": "Email sent successfully"}