name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:     
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cbeloni
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: danielr1996/envsubst-action@1.0.0
        env:
            IMAP_EMAIL: '${{vars.IMAP_EMAIL}}'
            IMAP_PASSWORD: '${{secrets.IMAP_PASSWORD}}'
            API_KEY: '${{secrets.API_KEY}}'
            FOLDER_ID: '${{vars.FOLDER_ID}}'
            HOST: '${{vars.HOST}}'
            USER: '${{vars.USER}}'
            PASSWORD: '${{secrets.PASSWORD}}'
            DATABASE: '${{vars.DATABASE}}'
            AWS_ACCESS_KEY_ID: '${{secrets.AWS_ACCESS_KEY_ID}}'
            AWS_SECRET_ACCESS_KEY: '${{secrets.AWS_SECRET_ACCESS_KEY}}'
            ENDPOINT_URL: '${{vars.ENDPOINT_URL}}'
        with:
          input: .env.template
          output: .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: cbeloni/auto-sindico:amd64

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_MGC }}" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_MGC }}      

      - name: Setup Kubeconfig 2
        run: |
          echo "${{ secrets.KUBECONFIG_MGC }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Apply Kubernetes manifests
        run: |          
          kubectl apply -f argocd-amd/auto-sindico-amd.yaml --validate=false
          kubectl rollout restart deployment/auto-sindico